spring.application.name=restaurant-reservation

# ===================================================================
# Active Profile: Default (Local & Production - PostgreSQL Configuration)
# ===================================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/restaurant_reservation
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# Security & Security Configuration (Asymmetric RSA JWT)
app.jwt.rsa.private-key-location=classpath:keys/private.pem
app.jwt.rsa.public-key-location=classpath:keys/public.pem
app.jwt.expiration-ms=86400000

# Documentation & Server Settings
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
server.port=8081

